name: Build

on: [workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-16.04
    environment: Production
    steps:

      - uses: actions/checkout@v2

      - name: Write Hello World
        shell: bash
        run: |
          echo "hello world" > hello-world.txt

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            hello-world.txt

      - name: Build
        shell: bash
        run: |
          echo "Build: ${{ secrets.PRODUCTION_SECRET }}"
 
  deploy:
    name: Deploy
    needs: Build
    runs-on: ubuntu-16.04
    environment: Deploy
    steps:

      - uses: actions/checkout@v2
      
      - uses: actions/download-artifact@v2
        with:
          name: dist

      - name: List Hello World
        shell: bash
        run: |
          ls -la

      - name: Deploy
        shell: bash
        run: |
          echo "Deploy: ${{ secrets.PRODUCTION_SECRET }}"
          